user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  16;
}

mail {
    auth_http localhost:9000;
    proxy_pass_error_message on;

    server {
        listen   127.0.0.1:143;
        protocol imap;
    }

    server {
        listen 127.0.0.1:25;
        protocol smtp;
        smtp_auth plain login;
    }
}
