site_name: École Di Croci
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top

nav:
  - MT4 — Streams / Parallèle / Complexité: index.html
  - MT3 — Git / OOP / Collections: mt3/index.html
