version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    devices:
      - /dev/hci0:/dev/hci0
      - /dev/hci1:/dev/hci1
    cap_add:
    - NET_ADMIN
    - NET_RAW
    ports:
    - 5353:5353/udp
    - 51827:51827
    volumes:
      - /home/drynish/docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /home/drynish/git:/git:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
    - 1883:1883
    volumes:
      - /home/drynish/docker/mosquitto/data:/mosquitto/data
      - /home/drynish/docker/mosquitto/log:/mosquitto/log
      - /home/drynish/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - caddy

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /home/drynish/docker/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=America/Montreal
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - caddy

networks:
  caddy:
    external: true
