[poller]
  debug   = false
  quiet   = false

[prometheus]
  disable     = false
  http_listen = "0.0.0.0:9130"

[influxdb]
  disable = true

[unifi.defaults]
  url    = "https://192.168.1.1"   # IP de ton contrôleur UniFi
  user   = "unifi-poller"
  pass   = "mudton-wAcby5-qovhyv"
  sites  = ["all"]
  save_sites      = true
  save_ids        = true
  save_events     = true
  save_alarms     = true
  save_anomalies  = true
  save_dpi        = true
  verify_ssl      = false           # Mettre true si tu as un cert valide
