version: '3'

services:
  nginx:
    container_name: family
    image: nginx:latest
    volumes:
      - /home/drynish/docker/famille/html:/usr/share/nginx/html
    restart: always
    networks:
      - caddy
    labels:
       caddy: dicroci.website
       caddy.reverse_proxy: "{{upstreams 80}}"
       caddy.tls.dns: ${CLOUDFLARE_API_TOKEN}

networks:
  caddy:
    external: true
