services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cpu_shares: 512
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8999:8999/tcp # Qbittorrent proxy
      - 6881:6881 # <-- port torrent (TCP/UDP)
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "wget -q --timeout=10 --spider https://ipinfo.io || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    volumes:
      - /home/drynish/docker/gluetun:/gluetun
    dns: 10.2.0.1
    networks:
      - caddy
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTON_WG_KEY}
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - SERVER_COUNTRIES=Sweden
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - TZ=America/Toronto
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,10.88.88.0/24
      - FIREWALL_INPUT_PORTS=8999
#     - VPN_SERVICE_PROVIDER=surshark #     - VPN_TYPE=wireguard
#      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
#      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
#      - DNS=10.2.0.1
#      - SERVER_COUNTRIES=switzerland
#      - TZ=AMERICA/Montreal
#      - UPDATER_PERIOD=24h
#      - HTTPPROXY=off #change to on if you wish to enble
#      - SHADOWSOCKS=off #change to on if you wish to enable

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=ETC/Montreal
      - WEBUI_PORT=8999
      - TORRENTING_PORT=6881
    volumes:
      - /home/drynish/docker/qbittorrent:/config
      - /home/drynish/mnt/Download:/downloads
    restart: unless-stopped
    cpu_shares: 256
    network_mode: "service:gluetun" # <-- ici
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  caddy:
    external: true
